wandb_version: 1

activation:
  desc: null
  value: SELU
initial_weights_regularizer:
  desc: null
  value: true
initialization:
  desc: null
  value: Glorot normal
iterations:
  desc: null
  value: 3000
LBFGS:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.001
num_dense_layers:
  desc: null
  value: 2
num_dense_nodes:
  desc: null
  value: 50
output_injection_gain:
  desc: null
  value: 50
resampling:
  desc: null
  value: true
resampler_period:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719599698
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 50
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
