_wandb:
    value:
        cli_version: 0.17.3
        python_version: 3.10.13
        t:
            1:
                - 1
                - 5
                - 50
                - 53
                - 55
            2:
                - 1
                - 5
                - 50
                - 53
                - 55
            3:
                - 2
                - 13
                - 16
                - 23
                - 55
            4: 3.10.13
            5: 0.17.3
            8:
                - 5
            12: 0.17.3
            13: linux-x86_64
data:
    value:
        L0: 1
        Tmax: 30
        Tmin: 22
        W: 0
        alpha: 1
        cb: 1
        d: 0.03
        h: 100
        k: 1
        p0: 0
        rhoc: 1
        steep: 20
        tauf: 1
        tchange: 0.25
network:
    value:
        LBFGS: false
        activation: SELU
        backend: pytorch
        initial_weights_regularizer: true
        initialization: Glorot normal
        iterations: 3000
        learning_rate: 0.001
        num_dense_layers: 2
        num_dense_nodes: 50
        output_injection_gain: 50
        resampler_period: 100
        resampling: true
run:
    value: BioHeat_PINNs_date_time_20240629_215418
