_wandb:
    value:
        cli_version: 0.17.6
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 50
                - 53
                - 55
            "2":
                - 1
                - 5
                - 50
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
                - 62
            "4": 3.10.13
            "5": 0.17.6
            "8":
                - 5
            "12": 0.17.6
            "13": linux-x86_64
network:
    value:
        LBFGS: false
        activation: SiLU
        backend: pytorch
        initial_weights_regularizer: true
        initialization: He normal
        iterations: 125
        learning_rate: 0.001
        num_dense_layers: 2
        num_dense_nodes: 50
        output_injection_gain: 50
        resampler_period: 100
        resampling: true
run:
    value: BioHeat_PINNs_date_time_20240818_130821
tuning:
    value:
        direction: minimize
        num_trials: 2
        study_name: BioHeat_Tuning_Study
