_wandb:
    value:
        cli_version: 0.17.6
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 50
                - 53
                - 55
            "2":
                - 1
                - 5
                - 50
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.17.6
            "8":
                - 5
            "12": 0.17.6
            "13": linux-x86_64
data:
    value:
        L0: 0.05
        Tmax: 45
        Tmin: 37
        W: 2.3154600000000003
        Wb: 0.00222
        alpha: 1
        cb: 3825
        d: 0.03
        h: 100
        k: 5
        p0: 0
        q0: 16
        rhob: 1043
        rhoc: 3820950
        steep: 20
        tauf: 1800
        tchange: 0.25
network:
    value:
        LBFGS: false
        activation: SiLU
        backend: pytorch
        initial_weights_regularizer: true
        initialization: He normal
        iterations: 150
        learning_rate: 0.001
        num_dense_layers: 2
        num_dense_nodes: 50
        output_injection_gain: 50
        resampler_period: 100
        resampling: true
run:
    value: BioHeat_PINNs_date_time_20240811_070801
tuning:
    value:
        direction: minimize
        num_trials: 2
        study_name: BioHeat_Tuning_Study
