_wandb:
    value:
        cli_version: 0.17.3
        python_version: 3.10.13
        t:
            1:
                - 1
                - 5
                - 50
                - 53
                - 55
            2:
                - 1
                - 5
                - 50
                - 53
                - 55
            3:
                - 13
                - 16
                - 23
                - 55
            4: 3.10.13
            5: 0.17.3
            8:
                - 5
            12: 0.17.3
            13: linux-x86_64
LBFGS:
    value: false
activation:
    value: SELU
initial_weights_regularizer:
    value: true
initialization:
    value: Glorot normal
iterations:
    value: 10
learning_rate:
    value: 0.001
num_dense_layers:
    value: 2
num_dense_nodes:
    value: 50
output_injection_gain:
    value: 50
resampler_period:
    value: 100
resampling:
    value: true
